ClusterName=docker-rocky8
SlurmctldHost=controller
SlurmUser=slurm
SlurmdUser=root
AuthType=auth/munge
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=pmi2
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
ReturnToService=2

SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldPort=6817
SlurmdPort=6818

InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=120
Waittime=0

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=controller
AccountingStoragePort=6819
JobAcctGatherType=jobacct_gather/none

NodeName=worker01 CPUs=2 RealMemory=1024 State=UNKNOWN
NodeName=worker02 CPUs=2 RealMemory=1024 State=UNKNOWN
PartitionName=debug Nodes=worker[01-02] Default=YES MaxTime=INFINITE State=UP
